#ifndef DEFINE_H
# define DEFINE_H

# include <unistd.h>
# define PAGESIZE sysconf(_SC_PAGESIZE)


# define HEADER_LEN 16
# define TINY_MAX_SIZE 2 * HEADER_LEN
# define TINY_MAX_LEN TINY_MAX_SIZE - HEADER_LEN
# define MEDIUM_MIN_SIZE TINY_MAX_SIZE + HEADER_LEN
# define MEDIUM_MAX_SIZE PAGESIZE
# define MEDIUM_MAX_LEN MEDIUM_MAX_SIZE - HEADER_LEN

enum mask_e {
	CHUNK_IN_USE_E,
	FIRST_IN_CHUNK_E,
	LAST_IN_CHUNK_E,
	FIRST_IN_ZONE_E,
	LAST_IN_ZONE_E,
	MASK_NB
};

# define MASK(x) 1 << x 
# define PREV_IN_USE 
# define CHUNK_IN_USE MASK(CHUNK_IN_USE_E)
# define FIRST_IN_CHUNK MASK(FIRST_IN_CHUNK_E)
# define LAST_IN_CHUNK MASK(LAST_IN_CHUNK_E)
# define FIRST_IN_ZONE MASK(FIRST_IN_ZONE_E)
# define LAST_IN_ZONE MASK(LAST_IN_ZONE_E)

# define SUCCESS 0

#endif
